const swaggerJsdoc = require('swagger-jsdoc');
const path = require('path');

const options = {
  definition: { openapi: '3.0.3' },
  apis: [
    path.join(process.cwd(), 'src/modules/**/*.routes.ts'),
    path.join(process.cwd(), 'src/modules/**/*.docs.ts'),
    path.join(process.cwd(), 'src/routes/*.ts')
  ]
};

const spec = swaggerJsdoc(options);
console.log('paths keys:', Object.keys(spec.paths));
console.log('paths length:', Object.keys(spec.paths).length);
// print first 1000 chars for inspection
const out = JSON.stringify(spec.paths, null, 2);
console.log(out.slice(0, 1000));

if (Object.keys(spec.paths).length === 0) {
  console.error('No paths were generated by swagger-jsdoc.');
  process.exit(1);
}

console.log('Done');
